version: '3.8'

services:
  pracujpl-bot:
    build: .
    environment:
      - WEBHOOK_URL
      - CHECK_INTERVAL_HOURS
    restart: unless-stopped
    container_name: pracujpl-bot
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
